name: Build APK From 

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ZIP extract karega
      - name: Extract Project ZIP
        run: |
          unzip *.zip -d project

      # Gradlew ko executable banayega
      - name: Make gradlew executable
        run: |
          cd project
          chmod +x ./gradlew

      # Java 17 setup
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build debug APK
      - name: Build Debug APK
        run: |
          cd project
          ./gradlew assembleDebug --stacktrace

      # APK upload karega GitHub artifacts me
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: AKCREATION-APP-debug
          path: project/app/build/outputs/apk/debug/*.apk
